lambdas:
  autodeploy-lambda:
    code: autodeploy-lambda
    handler: autodeploy.autodeploy_handler
    runtime: python
    description: Triggers a deployment to instances launched with certain Tags
    timeout: 300
    policies:
      ec2:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "ec2:DescribeInstances"
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
              - "ec2:TerminateInstances"
              - "ec2:StopInstances"
            Resource: "*"
            Effect: "Allow"
      cd:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "codedeploy:GetDeployment"
              - "codedeploy:GetDeploymentGroup"
              - "codedeploy:GetDeploymentConfig"
              - "codedeploy:GetApplicationRevision"
              - "codedeploy:CreateDeployment"
              - "codedeploy:UpdateDeploymentGroup"
              - "iam:PassRole"
            Resource: "*"
            Effect: "Allow"
